var user = new User();
/*Console.WriteLine($"User:\n\trank: {user.rank}\n\tprogress: {user.progress}");
Console.WriteLine("Attempt rank 1");
user.incProgress(1);
Console.WriteLine($"User:\n\trank: {user.rank}\n\tprogress: {user.progress}");
Console.WriteLine("Attempt rank 1");
user.incProgress(1);
Console.WriteLine($"User:\n\trank: {user.rank}\n\tprogress: {user.progress}");
Console.WriteLine("Attempt rank 1");
user.incProgress(1);
Console.WriteLine($"User:\n\trank: {user.rank}\n\tprogress: {user.progress}");
Console.WriteLine("Attempt rank 1");
user.incProgress(1);
Console.WriteLine($"User:\n\trank: {user.rank}\n\tprogress: {user.progress}");
Console.WriteLine("Attempt rank 1");
user.incProgress(1);
Console.WriteLine($"User:\n\trank: {user.rank}\n\tprogress: {user.progress}");
Console.WriteLine("Attempt rank 2");
user.incProgress(2);
Console.WriteLine($"User:\n\trank: {user.rank}\n\tprogress: {user.progress}");
Console.WriteLine("Attempt rank 2");
user.incProgress(2);
Console.WriteLine($"User:\n\trank: {user.rank}\n\tprogress: {user.progress}");
Console.WriteLine("Attempt rank -1");
user.incProgress(-1);*/
user.rank = 1;
user.progress = 20;
user.incProgress(-1);
Console.WriteLine($"User:\n\trank: {user.rank}\n\tprogress: {user.progress}");